### ISSUE TITLE
Hono POST requests not working

### ISSUE THREAD

**Issue by mariusbolik** [verydanny/appwrite-adapters#23]
Hello @verydanny,

thank you really much for creating these great adapters!

For testing purposes I am sending an image to the api and want to receive it back. Later I want to archive some image transformation features.

I am facing the issue that my POST requests are not working. It seems that they get handled as GET requests. Please see my demo project: https://github.com/mariusbolik/appwrite-hono-demo

<img width="1130" alt="Bildschirmfoto 2024-07-17 um 09 18 41" src="https://github.com/user-attachments/assets/4bc23e55-6494-4aea-9236-5c6f65956b36">
  
Kind regards,
Marius

**Comment by mariusbolik** [comment]
For now it seems like appwrite can only handle post bodies inthe form of text. 
It works when removing the `body.blob()` part.

**Comment by verydanny** [comment]
@mariusbolik Appwrite is working on adding binary uploads and hopefully streaming post bodies soon! I know for a fact that they will be adding  stream responses soon and POST binary up to 20mb.

I have already prepared the library for streaming and binary body. Just gotta wait :)

**Comment by mariusbolik** [comment]
Sounds great! Thank you!
